import org.example.SqlQueryNormalizer;
import org.junit.Assert;
import org.junit.Test;

public class SqlQueryNormalizerTest {

    @Test
    public void test() {
        String query = "SELECT t0.BUSPROCOPERID, t0.BUSPROCCODE, t0.BUSPROCOPERHASH, t0.BUSPROCINSTID, t0.BUSPROCOPERREVERSALNOTFL, t0.BUSPROCOPERDATE, t0.BUSPROCOPERREVERSALREASON, t0.BUSPROCOPERREVERSALDATE, t0.RECVER, t0.BALDEPID, t0.EQUIPSHIFTID, t0.EXTSYSCODE, t0.BUSPROCOPERSTATEID, t0.BUSPROCOPERCONTRUSERID, t0.USERID, t0.USERSHIFTID, t0.WORKPLACEID, t1.BUSPROCOPERID, t1.NATPERSONACCNTNUM, t1.BENEFICACCNTNUM, t1.BENEFICBANKCODE, t1.BENEFICNAME, t1.PAYMCARDCOMMISSUM, t1.PAYMCARDENDDATE, t1.PAYMCARDHOLDERNAME, t1.PAYMCARDMASKNUM, t1.PAYMCARDNUM, t1.PAYMCARDRRN, t1.WORKPLACECHECKCODE, t1.CLIENTNAME, t1.CREDITPRODUCTNAME, t1.DEBITPRODUCTNAME, t1.NATPERSONACCNTOPERPURPOSE, t1.NATPERSONACCNTOPERSUM, t1.NATPERSONACCNTACCESSTYPEID, t1.NATPERSONACCNTCURID, t1.NATPERSONACCNTDEPID, t1.BENEFICCLIENTID, t1.BENEFICACCNTEXTSYSCODE, t1.PAYMCARDSYSKINDID, t1.PAYMCARDISSUERBANKID, t1.CLIENTID, t1.NATPERSONACCNTEXTSYSCODE, t1.PAYMCARDCOMMISCURID, t1.NATPERSONCONTRACTID, t1.CREDITCASHSYMBOLCODE, t1.CREDITPRODUCTTYPEID, t1.CURID, t1.DEBITCASHSYMBOLCODE, t1.DEBITPRODUCTTYPEID, t1.EQUIPMENTID, t1.NATPERSONCONTRACTDEPID, t1.PAYMENTTYPEID, t1.NATPERSONACCNTOPERTYPEID FROM CM_BUSPROCOPER t0, CM_REGNATPERSONACCNTOPER t1 WHERE (((t0.BUSPROCINSTID = ?) AND (t1.BUSPROCOPERID = t0.BUSPROCOPERID)) AND (t0.BUSPROCCODE IN (?, ?, ?, ?, ?, ?, ?, ?, ?)))";
        String bind  = "98779, save-to-for-acc-oper, fill-client-account, client-account-debit, transfer-money, cash-person-deposit-nonowned-payin, transfer-money-by-barcode, fill-card-account, retail-account-for, card-cash-doc-to";
        String result = SqlQueryNormalizer.replaceParams(bind, query.toLowerCase(), 1);
        Assert.assertEquals("select t0.busprocoperid, t0.busproccode, t0.busprocoperhash, t0.busprocinstid, t0.busprocoperreversalnotfl, t0.busprocoperdate, t0.busprocoperreversalreason, t0.busprocoperreversaldate, t0.recver, t0.baldepid, t0.equipshiftid, t0.extsyscode, t0.busprocoperstateid, t0.busprocopercontruserid, t0.userid, t0.usershiftid, t0.workplaceid, t1.busprocoperid, t1.natpersonaccntnum, t1.beneficaccntnum, t1.beneficbankcode, t1.beneficname, t1.paymcardcommissum, t1.paymcardenddate, t1.paymcardholdername, t1.paymcardmasknum, t1.paymcardnum, t1.paymcardrrn, t1.workplacecheckcode, t1.clientname, t1.creditproductname, t1.debitproductname, t1.natpersonaccntoperpurpose, t1.natpersonaccntopersum, t1.natpersonaccntaccesstypeid, t1.natpersonaccntcurid, t1.natpersonaccntdepid, t1.beneficclientid, t1.beneficaccntextsyscode, t1.paymcardsyskindid, t1.paymcardissuerbankid, t1.clientid, t1.natpersonaccntextsyscode, t1.paymcardcommiscurid, t1.natpersoncontractid, t1.creditcashsymbolcode, t1.creditproducttypeid, t1.curid, t1.debitcashsymbolcode, t1.debitproducttypeid, t1.equipmentid, t1.natpersoncontractdepid, t1.paymenttypeid, t1.natpersonaccntopertypeid from cm_busprocoper t0, cm_regnatpersonaccntoper t1 where (((t0.busprocinstid = 98779) and (t1.busprocoperid = t0.busprocoperid)) and (t0.busproccode in ('save-to-for-acc-oper', 'fill-client-account', 'client-account-debit', 'transfer-money', 'cash-person-deposit-nonowned-payin', 'transfer-money-by-barcode', 'fill-card-account', 'retail-account-for', 'card-cash-doc-to')))", result);
    }
}